package exceptionfun;

public class MathFun {
	
	//Exceptions occur when code executes in an unexpected or unhappy(?) path
	//Happy path refers to programs working correctly with correct input
	
	/**
	 * @param args
	 */
	public static void main(String[] args) {
		int x = 5;
		int y = 0;
		
		//core structure of exception handling
		try {
			int result = x/y;
		} catch (ArithmeticException ae) {
			// TODO Auto-generated catch block
			System.out.println("Oops");
		} finally { //Will see this used to close resources a lot
			System.out.println("This code will always execute.");
		}
		
	}
	
	

}
